# Check the skipped instances from MA

In [7]:
data[0]['problem']

'sepsis'

In [2]:
import json
# missing_qn = []
missing_id = []
# Replace 'your_file.json' with the path to your JSON file
with open('/home/yl3427/cylab/SOAP_MA/Output/SOAP/3_problems_acute_kidney_injury_new_temp.json', 'r') as file:
    data = json.load(file)
# print("Total number of items:", len(data))

for idx, item in enumerate(data):
    # print(item['final']['final_choice'])
    if 'final' not in item.keys():
        print("Error in line", idx)
        print(item['hadm_id'])
        missing_id.append(item['adm_id'])
#     try:
#         question = item['Question']
#     except:
#         print("Error in line", idx)
#         print(item['qn_num'])
#         missing_qn.append(item['qn_num'])

In [18]:
# print(missing_qn)
print(missing_id)

[]


# Check the skipped instances from Baseline

In [3]:
import json
missing_item = []
# Replace 'your_file.json' with the path to your JSON file
with open('/home/yl3427/cylab/SOAP_MA/Output/SOAP/3_problems_sepsis_baseline.json', 'r') as file:
    data = json.load(file)

for idx, item in enumerate(data):
    if item["BaselineChoice"] == "Unknown":
        print("Error in line", idx)
        print(item['hadm_id'])
        missing_item.append(item['hadm_id'])

In [4]:
data[0]

{'note': 'pleuritic right chest pain\n- patient started on coumadin\n- [** 949**] briefly decreased (although unclear whether this was due to\naccidental foley removal), [** 949**] responded appropriately to 500 ml lr\nbolus with [** 949**] 60-70 cc\ns per hour this am\n- patient briefly developed non-gap acidosis with bicarb of 19,\nresolved with substitution of lr for ns for fluid boluses\ns: the patient is feeling well.  her chest pain has entirely resolved.\nshe continues to have dry-mouth as well as her baseline amount of cough\nand shortness or breath.  she has not had n/v diarrhea.  no pain or\nswelling in her legs.\nlosartan\nangioedema/lip\nlisinopril (oral)\ncough;\npenicillins\nitching;\nflagyl (oral) (metronidazole)\nwheezing;\nultram (oral) (tramadol hcl)\nrash;\nreview of systems is unchanged from admission except as noted below\nreview of systems:\nlast dose of antibiotics:\nciprofloxacin - [**2141-7-18**] 08:00 pm\nvancomycin - [**2141-7-19**] 08:02 am\ninfusions:\nhepa

In [16]:
import json
import copy
import os

def deep_merge(dict1, dict2):
    """
    Recursively merge dict2 into dict1.
    - If a key exists in both dicts and both values are themselves dicts, 
      recurse into those.
    - Otherwise, dict2’s value overwrites dict1’s value.
    """
    for key, value in dict2.items():
        if key not in dict1:
            dict1[key] = value
        else:
            if isinstance(dict1[key], dict) and isinstance(value, dict):
                deep_merge(dict1[key], value)
            else:
                # Overwrite dict1's value with dict2's value
                dict1[key] = value
    return dict1

def merge_json_files(file1, file2, output_file, identifier='qn_num'):
    """
    Merges two JSON files (each containing a list of dicts) 
    on a specified 'identifier' key. 
    If the key is missing from a particular dict, it will be skipped.
    """
    # 1) Load both JSON files
    with open(file1, "r", encoding="utf-8") as f:
        data1 = json.load(f)  # List of dicts
    with open(file2, "r", encoding="utf-8") as f:
        data2 = json.load(f)  # List of dicts

    # 2) Convert the first list into a dictionary keyed by 'identifier'
    merged_dict = {}
    for item in data1:
        if identifier in item:
            key_value = item[identifier]
            merged_dict[key_value] = copy.deepcopy(item)

    # 3) For each item in data2, either add or merge
    for item in data2:
        if identifier not in item:
            # Skip if 'identifier' doesn't exist in this item
            continue
        key_value = item[identifier]
        if key_value not in merged_dict:
            merged_dict[key_value] = copy.deepcopy(item)
        else:
            # Deep-merge fields from item into existing
            deep_merge(merged_dict[key_value], item)

    # 4) Convert the merged dictionary back to a list
    final_list = list(merged_dict.values())

    print(f"Merged {len(data1)} items from file1 and {len(data2)} items from file2.")
    print(f"Final list contains {len(final_list)} items.")

    # 5) Write to the output file
    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(final_list, f, indent=2, ensure_ascii=False)

if __name__ == "__main__":
    # Example usage:
    file1 = "/home/yl3427/cylab/SOAP_MA/Output/SOAP/chf_missing_final.json"
    file2 = "/home/yl3427/cylab/SOAP_MA/Output/SOAP/chf_final.json"
    output_file = "/home/yl3427/cylab/SOAP_MA/Output/SOAP/chf_final.json"

    # Example identifier: 'File ID' or 'qn_num'
    # If you need to merge on 'File ID', just pass identifier='File ID'.
    merge_json_files(file1, file2, output_file, identifier='File ID')
    print(f"Merged file saved as: {output_file}")


Merged 1 items from file1 and 351 items from file2.
Final list contains 351 items.
Merged file saved as: /home/yl3427/cylab/SOAP_MA/Output/SOAP/chf_final.json


In [17]:
import pandas as pd
# df = pd.read_csv("/home/yl3427/cylab/SOAP_MA/Input/SOAP_5_problems.csv")
df = pd.read_csv("/home/yl3427/cylab/SOAP_MA/Input/step3_ALL.csv")
len(df)

137

In [13]:
json_path = "/home/yl3427/cylab/SOAP_MA/Output/SOAP/sepsis_final.json"
with open(json_path, "r", encoding="utf-8") as f:
    data = json.load(f)
len(data)

351

# Evaluation

In [11]:
import json

def evaluate_SOAP_predictions(
    file_path,
    terms_lst: list
):
   
    def get_label(label_str, terms_lst):
        for term in terms_lst:
            if term.lower() in label_str.lower():
                return "Yes"
        return "No"

    def compute_confusion_matrix(data_list, baseline=False):
      
        tp = fp = tn = fn = other = 0

        for item in data_list:
            pred = item["BaselineChoice"] if baseline else item["final"]['final_choice']
            label = get_label(item["label"], terms_lst)

            if pred == "Yes" and label == "Yes":
                tp += 1
            elif pred == "Yes" and label == "No":
                fp += 1
            elif pred == "No" and label == "No":
                tn += 1
            elif pred == "No" and label == "Yes":
                fn += 1
            else:
                # e.g., pred is "Yes" but label is "Not sure", or vice versa
                other += 1

        return tp, tn, fp, fn, other

    def calculate_metrics(tp, tn, fp, fn):
        precision = tp / (tp + fp) if (tp + fp) else 0.0
        recall = tp / (tp + fn) if (tp + fn) else 0.0
        f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) else 0.0

        return {
            "Precision": precision,
            "Recall": recall,
            "F1 Score": f1
        }

    def print_results(title, tp, tn, fp, fn, other, metrics):
        """
        Nicely prints out the confusion matrix and performance metrics.
        """
        print(f"\n{title}")
        print("-" * len(title))
        print(f"{'True Positives (TP)':25} : {tp}")
        print(f"{'True Negatives (TN)':25} : {tn}")
        print(f"{'False Positives (FP)':25} : {fp}")
        print(f"{'False Negatives (FN)':25} : {fn}")
        # print(f"{'Other':25} : {other}")

        print()
        for metric_name, value in metrics.items():
            print(f"{metric_name:25} : {value:.3f}")

    # ----------------------------
    # 2. Load data from JSON file
    # ----------------------------
    with open(file_path, "r") as file:
        data = json.load(file)

    # ---------------------------------------------------
    # 3. Compute confusion matrix & metrics for aggregator
    # ---------------------------------------------------
    agg_tp, agg_tn, agg_fp, agg_fn, agg_other = compute_confusion_matrix(data)
    agg_metrics = calculate_metrics(agg_tp, agg_tn, agg_fp, agg_fn)

    # -------------------------------------------------
    # 4. Compute confusion matrix & metrics for baseline
    # -------------------------------------------------
    # base_tp, base_tn, base_fp, base_fn, base_other = compute_confusion_matrix(data, baseline=True)
    # base_metrics = calculate_metrics(base_tp, base_tn, base_fp, base_fn)

    print_results("Multi-Agents", agg_tp, agg_tn, agg_fp, agg_fn, agg_other, agg_metrics)
    # print_results("Baseline (ZS COT)", base_tp, base_tn, base_fp, base_fn, base_other, base_metrics)

In [10]:
mi = ["myocardial infarction", "elevation mi", "non-stemi", " NSTEMI", " stemi"]
chf = ["congestive heart failure", " chf", "HFrEF", "HFpEF"]
pulmonary_embolism = ["pulmonary embolism"]
pulmonary_hypertension = ["pulmonary hypertension", "pulmonary htn"]
sepsis = ["sepsis", "septic"]
urosepsis = ["urosepsis"]
meningitis = ["meningitis"]
aki = ["acute kidney injury", " aki", "acute renal failure", " arf"] # -> Acute tubular necrosis (ATN)인가 아닌가
atn = ["acute tubular necrosis", " atn"]
pancreatitis = ["pancreatitis"]
gi_bleed = ["gastrointestinal bleed", "gi bleed"]
hepatitis = ["hepatitis", " hep"]
cholangitis = ["cholangitis"]
asp_pneumonia = ["aspiration pneumonia"]

print("Sepsis")
evaluate_SOAP_predictions("/home/yl3427/cylab/SOAP_MA/Output/SOAP/3_problems_sepsis_baseline.json", sepsis)

print("AKI")
evaluate_SOAP_predictions("/home/yl3427/cylab/SOAP_MA/Output/SOAP/3_problems_acute_kidney_injury_baseline.json", aki)

print("Congestive Heart Failure")
evaluate_SOAP_predictions("/home/yl3427/cylab/SOAP_MA/Output/SOAP/3_problems_congestive_heart_failure_baseline.json", chf)

Sepsis

Multi-Agents
------------
True Positives (TP)       : 114
True Negatives (TN)       : 79
False Positives (FP)      : 83
False Negatives (FN)      : 12

Precision                 : 0.579
Recall                    : 0.905
F1 Score                  : 0.706

Baseline (ZS COT)
-----------------
True Positives (TP)       : 105
True Negatives (TN)       : 94
False Positives (FP)      : 68
False Negatives (FN)      : 21

Precision                 : 0.607
Recall                    : 0.833
F1 Score                  : 0.702
AKI

Multi-Agents
------------
True Positives (TP)       : 77
True Negatives (TN)       : 93
False Positives (FP)      : 63
False Negatives (FN)      : 55

Precision                 : 0.550
Recall                    : 0.583
F1 Score                  : 0.566

Baseline (ZS COT)
-----------------
True Positives (TP)       : 82
True Negatives (TN)       : 92
False Positives (FP)      : 64
False Negatives (FN)      : 50

Precision                 : 0.562
Recall             

In [13]:
mi = ["myocardial infarction", "elevation mi", "non-stemi", " NSTEMI", " stemi"]
chf = ["congestive heart failure", " chf", "HFrEF", "HFpEF"]
pulmonary_embolism = ["pulmonary embolism"]
pulmonary_hypertension = ["pulmonary hypertension", "pulmonary htn"]
sepsis = ["sepsis", "septic"]
urosepsis = ["urosepsis"]
meningitis = ["meningitis"]
aki = ["acute kidney injury", " aki", "acute renal failure", " arf"] # -> Acute tubular necrosis (ATN)인가 아닌가
atn = ["acute tubular necrosis", " atn"]
pancreatitis = ["pancreatitis"]
gi_bleed = ["gastrointestinal bleed", "gi bleed"]
hepatitis = ["hepatitis", " hep"]
cholangitis = ["cholangitis"]
asp_pneumonia = ["aspiration pneumonia"]
print("================New temp================")
print("Sepsis")
evaluate_SOAP_predictions("/home/yl3427/cylab/SOAP_MA/Output/SOAP/3_problems_sepsis_new_temp.json", sepsis)
print("AKI")
evaluate_SOAP_predictions("/home/yl3427/cylab/SOAP_MA/Output/SOAP/3_problems_acute_kidney_injury_new_temp.json", aki)
print("Congestive Heart Failure")
evaluate_SOAP_predictions("/home/yl3427/cylab/SOAP_MA/Output/SOAP/3_problems_congestive_heart_failure_new_temp.json", chf)

================New temp================
Sepsis

Multi-Agents
------------
True Positives (TP)       : 108
True Negatives (TN)       : 80
False Positives (FP)      : 82
False Negatives (FN)      : 18

Precision                 : 0.568
Recall                    : 0.857
F1 Score                  : 0.684
AKI

Multi-Agents
------------
True Positives (TP)       : 79
True Negatives (TN)       : 96
False Positives (FP)      : 60
False Negatives (FN)      : 53

Precision                 : 0.568
Recall                    : 0.598
F1 Score                  : 0.583
Congestive Heart Failure

Multi-Agents
------------
True Positives (TP)       : 36
True Negatives (TN)       : 167
False Positives (FP)      : 29
False Negatives (FN)      : 56

Precision                 : 0.554
Recall                    : 0.391
F1 Score                  : 0.459


### Medical QA

In [ ]:
# 시발 존나 짜증나네. 오지선다 아닌것도 있네 시발. 아오 좆같아시발.
with open("/home/yl3427/cylab/SOAP_MA/Output/MedicalQA/step1_final_with_baseline.json", 'r') as file:
    data = json.load(file)
# for k, v in data[0].items():
    # print(k, v)

import re

for item in data:
    text = item["Question"].split("\n")[-1]
    matches = re.findall(r'\b[A-Z](?=[.:])', text)
    print(matches)


In [8]:
import json
from collections import Counter
import numpy as np

# If you have scikit-learn installed:
from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    classification_report,
)

def evaluate_multiclass_predictions(
    data,
    aggregator_key="Aggregator",
    aggregator_prediction_key="final_choice",
    baseline_prediction_key="BaselineChoice",
    classes=["A","B","C","D","E"]
):
    
    # ------------------------------------
    # 2. Collect gold labels and predictions
    # ------------------------------------
    gold_labels_agg = []
    pred_labels_agg = []

    gold_labels_base = []
    pred_labels_base = []

    for item in data:
        # The gold label is presumably in item["Answer"], e.g. 'A', 'B', etc.
        gold = item["Answer"]
        
        # Aggregator's prediction
        # e.g. item["Aggregator"]["final_choice"] is 'A', 'B', 'C', etc.
        agg_pred = item[aggregator_key][aggregator_prediction_key]

        # Baseline's prediction
        base_pred = item[baseline_prediction_key]

        gold_labels_agg.append(gold)
        pred_labels_agg.append(agg_pred)

        gold_labels_base.append(gold)
        pred_labels_base.append(base_pred)

    # ------------------------------------------------
    # 3. Build confusion matrices & compute stats
    #    (Using scikit-learn for convenience)
    # ------------------------------------------------

    print("== Multi-Agents ==")
    cm_agg = confusion_matrix(gold_labels_agg, pred_labels_agg, labels=classes)
    print("Confusion Matrix (rows=True label, cols=Predicted):")
    print(cm_agg, "\n")

    accuracy_agg = accuracy_score(gold_labels_agg, pred_labels_agg)
    print(f"Accuracy: {accuracy_agg:.3f}\n")

    # classification_report prints precision, recall, f1 for each class,
    # plus macro/micro/weighted averages
    report_agg = classification_report(
        gold_labels_agg, 
        pred_labels_agg,
        labels=classes,
        zero_division=0  # to handle any class with no predictions
    )
    print(report_agg)

    print("\n== Baseline (ZS COT) ==")
    cm_base = confusion_matrix(gold_labels_base, pred_labels_base, labels=classes)
    print("Confusion Matrix (rows=True label, cols=Predicted):")
    print(cm_base, "\n")

    accuracy_base = accuracy_score(gold_labels_base, pred_labels_base)
    print(f"Accuracy: {accuracy_base:.3f}\n")

    report_base = classification_report(
        gold_labels_base, 
        pred_labels_base,
        labels=classes,
        zero_division=0
    )
    print(report_base)



In [13]:
import re
filtered_data = []
total_data_len = 0
for i in range(1, 4):
    with open("/home/yl3427/cylab/SOAP_MA/Output/MedicalQA/step3_final_with_baseline.json", 'r') as file:
        data = json.load(file)
    total_data_len += len(data)

    for item in data:
        text = item["Question"].split("\n")[-1]
        matches = re.findall(r'\b[A-Z](?=[.:])', text)
        if set(matches) == {'A', 'B', 'C', 'D', 'E'}:
            filtered_data.append(item)

evaluate_multiclass_predictions(filtered_data)

== Multi-Agents ==
Confusion Matrix (rows=True label, cols=Predicted):
[[60  0  0  6  0]
 [ 0 33  0  0  0]
 [ 3  0 69  0  0]
 [ 3  6  3 57  0]
 [ 0  0  0  3 75]] 

Accuracy: 0.925

              precision    recall  f1-score   support

           A       0.91      0.91      0.91        66
           B       0.85      1.00      0.92        33
           C       0.96      0.96      0.96        72
           D       0.86      0.83      0.84        69
           E       1.00      0.96      0.98        78

    accuracy                           0.92       318
   macro avg       0.92      0.93      0.92       318
weighted avg       0.93      0.92      0.92       318


== Baseline (ZS COT) ==
Confusion Matrix (rows=True label, cols=Predicted):
[[57  3  3  3  0]
 [ 0 33  0  0  0]
 [ 3  0 66  3  0]
 [ 3  3  3 60  0]
 [ 0  0  0  3 75]] 

Accuracy: 0.915

              precision    recall  f1-score   support

           A       0.90      0.86      0.88        66
           B       0.85      1.00 

In [74]:
len(filtered_data), total_data_len

(267, 357)