# Check the skipped instances from MA

In [ ]:
import json
# missing_qn = []
missing_id = []
# Replace 'your_file.json' with the path to your JSON file
with open('/home/yl3427/cylab/SOAP_MA/Output/SOAP/sepsis_final.json', 'r') as file:
    data = json.load(file)

for idx, item in enumerate(data):
    if len(item.keys()) != 9:
        print("Error in line", idx)
        print(item['File ID'])
        missing_id.append(item['File ID'])
#     try:
#         question = item['Question']
#     except:
#         print("Error in line", idx)
#         print(item['qn_num'])
#         missing_qn.append(item['qn_num'])

Error in line 0
110458.txt
Error in line 1
121860.txt
Error in line 2
126165.txt
Error in line 3
139318.txt
Error in line 4
167352.txt
Error in line 5
103771.txt
Error in line 6
186757.txt
Error in line 7
147724.txt
Error in line 8
148588.txt
Error in line 9
148762.txt
Error in line 10
111314.txt
Error in line 11
189576.txt
Error in line 12
149828.txt
Error in line 13
192754.txt
Error in line 14
110437.txt
Error in line 15
103853.txt
Error in line 16
102567.txt
Error in line 17
104263.txt
Error in line 18
105141.txt
Error in line 19
104502.txt
Error in line 20
148180.txt
Error in line 21
103810.txt
Error in line 22
187363.txt
Error in line 23
192929.txt
Error in line 24
193271.txt
Error in line 25
100791.txt
Error in line 26
199574.txt
Error in line 27
106015.txt
Error in line 28
111144.txt
Error in line 29
111312.txt
Error in line 30
117379.txt
Error in line 31
125385.txt
Error in line 32
127339.txt
Error in line 33
135439.txt
Error in line 34
135960.txt
Error in line 35
136659.txt
Er

In [2]:
# print(missing_qn)
print(missing_id)

['110458.txt', '121860.txt', '126165.txt', '139318.txt', '167352.txt', '103771.txt', '186757.txt', '147724.txt', '148588.txt', '148762.txt', '111314.txt', '189576.txt', '149828.txt', '192754.txt', '110437.txt', '103853.txt', '102567.txt', '104263.txt', '105141.txt', '104502.txt', '148180.txt', '103810.txt', '187363.txt', '192929.txt', '193271.txt', '100791.txt', '199574.txt', '106015.txt', '111144.txt', '111312.txt', '117379.txt', '125385.txt', '127339.txt', '135439.txt', '135960.txt', '136659.txt', '138155.txt', '144187.txt', '145644.txt', '149017.txt', '150509.txt', '151045.txt', '156297.txt', '157453.txt', '159591.txt', '169374.txt', '171971.txt', '175448.txt', '192698.txt', '199640.txt', '101616.txt', '102486.txt', '198989.txt', '100326.txt', '109934.txt', '191238.txt', '188769.txt', '109249.txt', '199699.txt', '193820.txt', '185887.txt', '190911.txt', '192874.txt', '110692.txt', '187277.txt', '148348.txt', '193955.txt', '110484.txt', '193799.txt', '187707.txt', '185892.txt', '1864

In [3]:
len(missing_id)

351

In [ ]:
for idx, item in enumerate(data):
    if item['Fi

351

# Check the skipped instances from Baseline

In [3]:
import json
missing_item = []
# Replace 'your_file.json' with the path to your JSON file
with open('/home/yl3427/cylab/SOAP_MA/Output/TNM/brca_only_with_baseline.json', 'r') as file:
    data = json.load(file)

for idx, item in enumerate(data):
    if item["BaselineChoice"] == "Unknown":
        print("Error in line", idx)
        print(item['filename'])
        missing_item.append(item['filename'])

In [7]:
error_cnt = 0
for idx, item in enumerate(data):
    label = f"T{item['Answer']+1}"
    baseline_pred = item['BaselineChoice']
    if label != baseline_pred:
        print(label, baseline_pred)
        error_cnt += 1
print(error_cnt)

T2 T1
T2 T1
T3 T1
T3 T2
T2 T1
T3 T2
T2 T4
T1 T2
T3 T2
T3 T2
T1 T2
T1 T2
T1 T2
T2 T4
T1 T4
T4 T2
T3 T2
T4 T3
T2 T4
T3 T2
T1 T2
T2 T1
T2 T1
T1 T2
T2 T4
T3 T2
T1 T2
T3 T4
T3 T2
T1 T2
T4 T2
T3 T1
T2 T4
T1 T2
T1 T2
T2 T3
T3 T4
T1 T2
T1 T2
T1 T2
T3 T2
T2 T1
T3 T4
T3 T4
T3 T2
T3 T1
T1 T2
T3 T2
T4 T2
T4 T2
T3 T2
T1 T2
T3 T1
T3 T1
T1 T2
T2 T1
T3 T1
T1 T2
T3 T1
T3 T2
T1 T2
T3 T4
T1 T2
T1 T2
T1 T2
T2 T1
T1 T2
T1 T2
T3 T2
T3 T2
T1 T2
T2 T3
T1 T2
T3 T2
T1 T2
T2 T4
T4 T2
T4 T1
T2 T3
T3 T4
T1 T3
T1 T2
T3 T4
T1 T2
T1 T2
T2 T4
T3 T2
T2 T4
T1 T2
T1 T2
T2 T4
T4 T3
T2 T1
T2 T4
T2 T1
T2 T1
T2 T4
T2 T4
T1 T2
T3 T4
T2 T3
T1 T2
T1 T2
T1 T2
T2 T1
T2 T1
T1 T2
T1 T4
T4 T2
T4 T2
T3 T2
T4 T2
T2 T1
T3 T2
114


In [2]:
len(missing_item)

0

In [7]:
missing_qn = []

In [8]:
input_json_path = "sample_data.json"
f"{input_json_path.split('.')[0]}_with_baseline.json"


'sample_data_with_baseline.json'

In [4]:
import pandas as pd
df = pd.read_csv("/home/yl3427/cylab/llm_reasoning/reasoning/data/step3_ALL.csv")
len(df)

137

In [4]:
input_json_path.split(".")

['sample_data', 'json']

In [11]:
import json
import copy
import os

def deep_merge(dict1, dict2):
    """
    Recursively merge dict2 into dict1.
    - If a key exists in both dicts and both values are themselves dicts, 
      recurse into those.
    - Otherwise, dict2’s value overwrites dict1’s value.
    """
    for key, value in dict2.items():
        if key not in dict1:
            dict1[key] = value
        else:
            if isinstance(dict1[key], dict) and isinstance(value, dict):
                deep_merge(dict1[key], value)
            else:
                # Overwrite dict1's value with dict2's value
                dict1[key] = value
    return dict1

def merge_json_files(file1, file2, output_file, identifier='qn_num'):
    """
    Merges two JSON files (each containing a list of dicts) 
    on a specified 'identifier' key. 
    If the key is missing from a particular dict, it will be skipped.
    """
    # 1) Load both JSON files
    with open(file1, "r", encoding="utf-8") as f:
        data1 = json.load(f)  # List of dicts
    with open(file2, "r", encoding="utf-8") as f:
        data2 = json.load(f)  # List of dicts

    # 2) Convert the first list into a dictionary keyed by 'identifier'
    merged_dict = {}
    for item in data1:
        if identifier in item:
            key_value = item[identifier]
            merged_dict[key_value] = copy.deepcopy(item)

    # 3) For each item in data2, either add or merge
    for item in data2:
        if identifier not in item:
            # Skip if 'identifier' doesn't exist in this item
            continue
        key_value = item[identifier]
        if key_value not in merged_dict:
            merged_dict[key_value] = copy.deepcopy(item)
        else:
            # Deep-merge fields from item into existing
            deep_merge(merged_dict[key_value], item)

    # 4) Convert the merged dictionary back to a list
    final_list = list(merged_dict.values())

    print(f"Merged {len(data1)} items from file1 and {len(data2)} items from file2.")
    print(f"Final list contains {len(final_list)} items.")

    # 5) Write to the output file
    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(final_list, f, indent=2, ensure_ascii=False)

if __name__ == "__main__":
    # Example usage:
    file1 = "/home/yl3427/cylab/SOAP_MA/Output/SOAP/sepsis_missing_final.json"
    file2 = "/home/yl3427/cylab/SOAP_MA/Output/SOAP/sepsis_final.json"
    output_file = "/home/yl3427/cylab/SOAP_MA/Output/SOAP/sepsis_final.json"

    # Example identifier: 'File ID' or 'qn_num'
    # If you need to merge on 'File ID', just pass identifier='File ID'.
    merge_json_files(file1, file2, output_file, identifier='File ID')
    print(f"Merged file saved as: {output_file}")


Merged 5 items from file1 and 351 items from file2.
Final list contains 351 items.
Merged file saved as: /home/yl3427/cylab/SOAP_MA/Output/SOAP/sepsis_final.json


In [17]:
import pandas as pd
# df = pd.read_csv("/home/yl3427/cylab/SOAP_MA/Input/SOAP_5_problems.csv")
df = pd.read_csv("/home/yl3427/cylab/SOAP_MA/Input/step3_ALL.csv")
len(df)

137

In [13]:
json_path = "/home/yl3427/cylab/SOAP_MA/Output/SOAP/sepsis_final.json"
with open(json_path, "r", encoding="utf-8") as f:
    data = json.load(f)
len(data)

351

# Evaluation

In [30]:
with open("/home/yl3427/cylab/SOAP_MA/Output/MedicalQA/step1_final_with_baseline.json", 'r') as file:
    data = json.load(file)
for k, v in data[0].items():
    print(k, v)

Gastroenterologist {'expertise': ['Gallstones', 'Abdominal pain', 'Nausea', 'Ultrasonography', 'Bile duct disorders'], 'original_response': {'reasoning': "To solve this question, let's break down the key components of the scenario provided and analyze them step by step from a gastroenterological perspective:\\/n\\n1. **Patient Profile**: The patient is an 18-year-old woman with sickle cell disease. Sickle cell disease is known to increase the risk of certain gastrointestinal issues, including gallstones, due to the chronic hemolysis that leads to an increased bilirubin load on the liver. This can result in the formation of pigment gallstones. However, the presence of gallstones can also be influenced by other factors such as diet, genetics, and other medical conditions.\\n\\n2. **Symptoms**: The patient presents with severe abdominal pain and nausea. These symptoms are classic for biliary colic or a gallbladder attack, which often occurs when a gallstone temporarily blocks the cystic d

In [50]:
with open('/home/yl3427/cylab/SOAP_MA/Output/SOAP/sepsis_final_with_baseline.json', 'r') as file:
    data = json.load(file)
tp = 0
fp = 0
tn = 0
fn = 0
_ = 0

for item_dict in data:
    pred = item_dict['Aggregator']['final_choice']
    if 'sepsis' in item_dict['Answer']:
        label = "Yes"
    elif 'septic' in item_dict['Answer']:
        label = "Not sure"
    else:
        label = "No"

    if pred == "Yes" and label == "Yes":
        tp += 1
    elif pred == "Yes" and label == "No":
        fp += 1
    elif pred == "No" and label == "No":
        tn += 1
    elif pred == "No" and label == "Yes":
        fn += 1
    else:
        _ += 1

print("True positives:", tp)
print("True negatives:", tn)
print("False positives:", fp)
print("False negatives:", fn)
print("Other:", _)

# Calculate precision, recall, and F1 score
precision = tp / (tp + fp)
recall = tp / (tp + fn)
f1 = 2 * (precision * recall) / (precision + recall)

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

True positives: 81
True negatives: 141
False positives: 83
False negatives: 23
Other: 23
Precision: 0.49390243902439024
Recall: 0.7788461538461539
F1 Score: 0.6044776119402985


In [43]:
with open('/home/yl3427/cylab/SOAP_MA/Output/SOAP/sepsis_final_with_baseline.json', 'r') as file:
    data = json.load(file)
tp = 0
fp = 0
tn = 0
fn = 0
_ = 0

for item_dict in data:
    pred = item_dict['BaselineChoice']
    if 'sepsis' in item_dict['Answer']:
        label = "Yes"
    elif 'septic' in item_dict['Answer']:
        label = "Not sure"
    else:
        label = "No"

    if pred == "Yes" and label == "Yes":
        tp += 1
    elif pred == "Yes" and label == "No":
        fp += 1
    elif pred == "No" and label == "No":
        tn += 1
    elif pred == "No" and label == "Yes":
        fn += 1
    else:
        _ += 1

print("True positives:", tp)
print("True negatives:", tn)
print("False positives:", fp)
print("False negatives:", fn)
print("Other:", _)

# Calculate precision, recall, and F1 score
precision = tp / (tp + fp)
recall = tp / (tp + fn)
f1 = 2 * (precision * recall) / (precision + recall)

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

True positives: 80
True negatives: 131
False positives: 93
False negatives: 24
Other: 23
Precision: 0.4624277456647399
Recall: 0.7692307692307693
F1 Score: 0.5776173285198556


In [49]:
import json

def evaluate_sepsis_predictions(
    file_path,
    aggregator_key="Aggregator",
    aggregator_prediction_key="final_choice",
    baseline_prediction_key="BaselineChoice",
):
   
    def get_label(answer):
        if "sepsis" in answer:
            return "Yes"
        elif "septic" in answer:
            return "Not sure"
        else:
            return "No"

    def compute_confusion_matrix(data_list, prediction_key, is_aggregator=True):
      
        tp = fp = tn = fn = other = 0

        for item in data_list:
            if is_aggregator:
                # aggregator prediction is nested: item[aggregator_key][aggregator_prediction_key]
                pred = item[aggregator_key][aggregator_prediction_key]
            else:
                # baseline prediction is top-level: item[baseline_prediction_key]
                pred = item[baseline_prediction_key]

            label = get_label(item["Answer"])

            if pred == "Yes" and label == "Yes":
                tp += 1
            elif pred == "Yes" and label == "No":
                fp += 1
            elif pred == "No" and label == "No":
                tn += 1
            elif pred == "No" and label == "Yes":
                fn += 1
            else:
                # e.g., pred is "Yes" but label is "Not sure", or vice versa
                other += 1

        return tp, tn, fp, fn, other

    def calculate_metrics(tp, tn, fp, fn):
        precision = tp / (tp + fp) if (tp + fp) else 0.0
        recall = tp / (tp + fn) if (tp + fn) else 0.0
        f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) else 0.0

        return {
            "Precision": precision,
            "Recall": recall,
            "F1 Score": f1
        }

    def print_results(title, tp, tn, fp, fn, other, metrics):
        """
        Nicely prints out the confusion matrix and performance metrics.
        """
        print(f"\n{title}")
        print("-" * len(title))
        print(f"{'True Positives (TP)':25} : {tp}")
        print(f"{'True Negatives (TN)':25} : {tn}")
        print(f"{'False Positives (FP)':25} : {fp}")
        print(f"{'False Negatives (FN)':25} : {fn}")
        print(f"{'Other':25} : {other}")

        print()
        for metric_name, value in metrics.items():
            print(f"{metric_name:25} : {value:.3f}")

    # ----------------------------
    # 2. Load data from JSON file
    # ----------------------------
    with open(file_path, "r") as file:
        data = json.load(file)

    # ---------------------------------------------------
    # 3. Compute confusion matrix & metrics for aggregator
    # ---------------------------------------------------
    agg_tp, agg_tn, agg_fp, agg_fn, agg_other = compute_confusion_matrix(
        data, aggregator_prediction_key, is_aggregator=True
    )
    agg_metrics = calculate_metrics(agg_tp, agg_tn, agg_fp, agg_fn)

    # -------------------------------------------------
    # 4. Compute confusion matrix & metrics for baseline
    # -------------------------------------------------
    base_tp, base_tn, base_fp, base_fn, base_other = compute_confusion_matrix(
        data, baseline_prediction_key, is_aggregator=False
    )
    base_metrics = calculate_metrics(base_tp, base_tn, base_fp, base_fn)

    print_results("Aggregator Agent Performance", agg_tp, agg_tn, agg_fp, agg_fn, agg_other, agg_metrics)
    print_results("Baseline Performance", base_tp, base_tn, base_fp, base_fn, base_other, base_metrics)


# -----------------------
# Example Usage:
# -----------------------
evaluate_sepsis_predictions("/home/yl3427/cylab/SOAP_MA/Output/SOAP/sepsis_final_with_baseline.json")



Aggregator Agent Performance
----------------------------
True Positives (TP)       : 81
True Negatives (TN)       : 141
False Positives (FP)      : 83
False Negatives (FN)      : 23
Other                     : 23

Precision                 : 0.494
Recall                    : 0.779
F1 Score                  : 0.604

Baseline Performance
--------------------
True Positives (TP)       : 80
True Negatives (TN)       : 131
False Positives (FP)      : 93
False Negatives (FN)      : 24
Other                     : 23

Precision                 : 0.462
Recall                    : 0.769
F1 Score                  : 0.578


In [ ]:
import json

def evaluate_sepsis_predictions(
    file_path,
    aggregator_key="Aggregator",
    aggregator_prediction_key="final_choice",
    baseline_prediction_key="BaselineChoice",
):

    def compute_confusion_matrix(data_list, prediction_key, is_aggregator=True):
      
        tp = fp = tn = fn = other = 0

        for item in data_list:
            if is_aggregator:
                # aggregator prediction is nested: item[aggregator_key][aggregator_prediction_key]
                pred = item[aggregator_key][aggregator_prediction_key]
            else:
                # baseline prediction is top-level: item[baseline_prediction_key]
                pred = item[baseline_prediction_key]

            label = item["Answer"]

            if pred == label:
                tp += 1
            elif pred == "Yes" and label == "No":
                fp += 1
            elif pred == "No" and label == "No":
                tn += 1
            elif pred == "No" and label == "Yes":
                fn += 1
            else:
                # e.g., pred is "Yes" but label is "Not sure", or vice versa
                other += 1

        return tp, tn, fp, fn, other

    def calculate_metrics(tp, tn, fp, fn):
        precision = tp / (tp + fp) if (tp + fp) else 0.0
        recall = tp / (tp + fn) if (tp + fn) else 0.0
        f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) else 0.0

        return {
            "Precision": precision,
            "Recall": recall,
            "F1 Score": f1
        }

    def print_results(title, tp, tn, fp, fn, other, metrics):
        """
        Nicely prints out the confusion matrix and performance metrics.
        """
        print(f"\n{title}")
        print("-" * len(title))
        print(f"{'True Positives (TP)':25} : {tp}")
        print(f"{'True Negatives (TN)':25} : {tn}")
        print(f"{'False Positives (FP)':25} : {fp}")
        print(f"{'False Negatives (FN)':25} : {fn}")
        print(f"{'Other':25} : {other}")

        print()
        for metric_name, value in metrics.items():
            print(f"{metric_name:25} : {value:.3f}")

    # ----------------------------
    # 2. Load data from JSON file
    # ----------------------------
    with open(file_path, "r") as file:
        data = json.load(file)

    # ---------------------------------------------------
    # 3. Compute confusion matrix & metrics for aggregator
    # ---------------------------------------------------
    agg_tp, agg_tn, agg_fp, agg_fn, agg_other = compute_confusion_matrix(
        data, aggregator_prediction_key, is_aggregator=True
    )
    agg_metrics = calculate_metrics(agg_tp, agg_tn, agg_fp, agg_fn)

    # -------------------------------------------------
    # 4. Compute confusion matrix & metrics for baseline
    # -------------------------------------------------
    base_tp, base_tn, base_fp, base_fn, base_other = compute_confusion_matrix(
        data, baseline_prediction_key, is_aggregator=False
    )
    base_metrics = calculate_metrics(base_tp, base_tn, base_fp, base_fn)

    print_results("Aggregator Agent Performance", agg_tp, agg_tn, agg_fp, agg_fn, agg_other, agg_metrics)
    print_results("Baseline Performance", base_tp, base_tn, base_fp, base_fn, base_other, base_metrics)


# -----------------------
# Example Usage:
# -----------------------
evaluate_sepsis_predictions("/home/yl3427/cylab/SOAP_MA/Output/MedicalQA/step1_final_with_baseline.json")


In [64]:
# 시발 존나 짜증나네. 오지선다 아닌것도 있네 시발. 아오 좆같아시발.
with open("/home/yl3427/cylab/SOAP_MA/Output/MedicalQA/step1_final_with_baseline.json", 'r') as file:
    data = json.load(file)
# for k, v in data[0].items():
    # print(k, v)

import re

for item in data:
    text = item["Question"].split("\n")[-1]
    matches = re.findall(r'\b[A-Z](?=[.:])', text)
    print(matches)


['A', 'B', 'C', 'D', 'E']
['A', 'B', 'C', 'D', 'E']
['A', 'B', 'C', 'D', 'E']
['A', 'B', 'C', 'D', 'E']
['A', 'B', 'C', 'D']
['A', 'B', 'C', 'D', 'E', 'F']
['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
['A', 'B', 'C', 'D', 'E', 'F']
['A', 'B', 'C', 'D', 'E']
['A', 'B', 'C', 'D', 'E', 'F']
['A', 'B', 'C', 'D', 'E']
['A', 'B', 'C', 'D', 'E']
['A', 'B', 'C', 'D']
['A', 'B', 'C', 'D', 'E']
['A', 'B', 'C', 'D', 'E']
['A', 'B', 'C', 'D', 'E', 'F']
['A', 'B', 'C', 'D', 'E']
['A', 'B', 'C', 'D', 'E']
['A', 'B', 'C', 'D', 'E', 'F', 'G']
['A', 'B', 'C', 'D', 'E']
['A', 'B', 'C', 'D', 'E']
['A', 'B', 'C', 'D', 'E']
['A', 'B', 'C', 'D', 'E']
['A', 'B', 'C', 'D', 'E']
['A', 'B', 'C', 'D', 'E']
['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']
['A', 'B', 'C', 'D', 'E']
['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
['A', 'B', 'C', 'D', 'E']
['A', 'B', 'C', 'D', 'E']
['A', 'B', 'C', 'D', 'E']
['A', 'B', 'C', 'D', 'E']
['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']
['A', 'B', 'C', 'D', 'E']
['A', 'B', 'C', 'D', 'E']


In [75]:
import json
from collections import Counter
import numpy as np

# If you have scikit-learn installed:
from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    classification_report,
)

def evaluate_multiclass_predictions(
    data,
    aggregator_key="Aggregator",
    aggregator_prediction_key="final_choice",
    baseline_prediction_key="BaselineChoice",
    classes=["A","B","C","D","E"]
):
    
    # ------------------------------------
    # 2. Collect gold labels and predictions
    # ------------------------------------
    gold_labels_agg = []
    pred_labels_agg = []

    gold_labels_base = []
    pred_labels_base = []

    for item in data:
        # The gold label is presumably in item["Answer"], e.g. 'A', 'B', etc.
        gold = item["Answer"]
        
        # Aggregator's prediction
        # e.g. item["Aggregator"]["final_choice"] is 'A', 'B', 'C', etc.
        agg_pred = item[aggregator_key][aggregator_prediction_key]

        # Baseline's prediction
        base_pred = item[baseline_prediction_key]

        gold_labels_agg.append(gold)
        pred_labels_agg.append(agg_pred)

        gold_labels_base.append(gold)
        pred_labels_base.append(base_pred)

    # ------------------------------------------------
    # 3. Build confusion matrices & compute stats
    #    (Using scikit-learn for convenience)
    # ------------------------------------------------

    print("== Aggregator Results ==")
    cm_agg = confusion_matrix(gold_labels_agg, pred_labels_agg, labels=classes)
    print("Confusion Matrix (rows=True label, cols=Predicted):")
    print(cm_agg, "\n")

    accuracy_agg = accuracy_score(gold_labels_agg, pred_labels_agg)
    print(f"Accuracy: {accuracy_agg:.3f}\n")

    # classification_report prints precision, recall, f1 for each class,
    # plus macro/micro/weighted averages
    report_agg = classification_report(
        gold_labels_agg, 
        pred_labels_agg,
        labels=classes,
        zero_division=0  # to handle any class with no predictions
    )
    print(report_agg)

    print("\n== Baseline Results ==")
    cm_base = confusion_matrix(gold_labels_base, pred_labels_base, labels=classes)
    print("Confusion Matrix (rows=True label, cols=Predicted):")
    print(cm_base, "\n")

    accuracy_base = accuracy_score(gold_labels_base, pred_labels_base)
    print(f"Accuracy: {accuracy_base:.3f}\n")

    report_base = classification_report(
        gold_labels_base, 
        pred_labels_base,
        labels=classes,
        zero_division=0
    )
    print(report_base)



In [76]:
import re
filtered_data = []
total_data_len = 0
for i in range(1, 4):
    with open("/home/yl3427/cylab/SOAP_MA/Output/MedicalQA/step1_final_with_baseline.json", 'r') as file:
        data = json.load(file)
    total_data_len += len(data)

    for item in data:
        text = item["Question"].split("\n")[-1]
        matches = re.findall(r'\b[A-Z](?=[.:])', text)
        if set(matches) == {'A', 'B', 'C', 'D', 'E'}:
            filtered_data.append(item)

evaluate_multiclass_predictions(filtered_data)

== Aggregator Results ==
Confusion Matrix (rows=True label, cols=Predicted):
[[63  0  0  0  3]
 [ 0 48  3  0  0]
 [ 6  0 36  0  0]
 [ 0  0  6 63  0]
 [ 0  3  3  0 33]] 

Accuracy: 0.910

              precision    recall  f1-score   support

           A       0.91      0.95      0.93        66
           B       0.94      0.94      0.94        51
           C       0.75      0.86      0.80        42
           D       1.00      0.91      0.95        69
           E       0.92      0.85      0.88        39

    accuracy                           0.91       267
   macro avg       0.90      0.90      0.90       267
weighted avg       0.92      0.91      0.91       267


== Baseline Results ==
Confusion Matrix (rows=True label, cols=Predicted):
[[60  0  3  0  3]
 [ 0 48  3  0  0]
 [ 3  3 36  0  0]
 [ 0  3  6 57  3]
 [ 0  3  3  0 33]] 

Accuracy: 0.876

              precision    recall  f1-score   support

           A       0.95      0.91      0.93        66
           B       0.84      

In [74]:
len(filtered_data), total_data_len

(267, 357)